-- V1 baseline: exact schema snapshot of the live Neon database, taken 2026-08-17 with
-- pg_dump --schema-only. Supersedes the old V1..V10 chain (squashed on repo re-init); the
-- pre-Flyway hand-applied files under backend/backlog/db/migrations/ are folded in here too.
--
-- Neon is baselined at V1 (spring.flyway.baseline-on-migrate=true, baseline-version=1), so this
-- file is RECORDED there, never executed. It DOES execute on any empty database -- the test
-- profile (baseline-on-migrate=false) runs it from zero, then Hibernate ddl-auto=validate checks
-- it against every entity mapping. That is what proves this snapshot is complete.
--
-- FROZEN once applied: Flyway checksums the whole file, comments included. Any later change is V2.
--
--

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

--
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    contact_email character varying(255),
    dept_name character varying(255) NOT NULL,
    dept_code character varying(255) NOT NULL,
    version bigint DEFAULT 0
);

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: exam_cycles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_cycles (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone,
    exam_month_year character varying(255),
    name character varying(255) NOT NULL
);

--
-- Name: exam_cycles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_cycles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_cycles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: proctor_students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proctor_students (
    roll_no character varying(255) NOT NULL,
    proctor_username character varying(255) NOT NULL,
    assigned_by character varying(255),
    assigned_at timestamp(6) without time zone DEFAULT now() NOT NULL
);

--
-- Name: progression_batch_students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progression_batch_students (
    id bigint NOT NULL,
    batch_id bigint NOT NULL,
    roll_no character varying(255) NOT NULL,
    semester_from integer NOT NULL,
    semester_to integer,
    outcome character varying(255) NOT NULL,
    CONSTRAINT chk_progression_batch_students_outcome CHECK (((outcome)::text = ANY (ARRAY[('PROMOTED'::character varying)::text, ('EXCLUDED_BY_ADMIN'::character varying)::text, ('SKIPPED_AT_MAX'::character varying)::text, ('SKIPPED_INVALID_SEMESTER'::character varying)::text]))),
    CONSTRAINT chk_progression_batch_students_semester_to CHECK (((((outcome)::text = 'PROMOTED'::text) AND (semester_to = (semester_from + 2))) OR (((outcome)::text <> 'PROMOTED'::text) AND (semester_to IS NULL))))
);

--
-- Name: progression_batch_students_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.progression_batch_students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progression_batch_students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: progression_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progression_batches (
    id bigint NOT NULL,
    actor_username character varying(255) NOT NULL,
    run_at timestamp(6) with time zone NOT NULL,
    filter_semester integer,
    filter_dept_code character varying(255),
    promoted_count integer NOT NULL,
    excluded_count integer NOT NULL,
    skipped_count integer NOT NULL,
    CONSTRAINT chk_progression_batches_filter_semester CHECK (((filter_semester IS NULL) OR (filter_semester = ANY (ARRAY[2, 4, 6, 8]))))
);

--
-- Name: progression_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.progression_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progression_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: registration_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registration_events (
    id bigint NOT NULL,
    action character varying(255),
    actor character varying(255),
    actor_role character varying(255),
    note character varying(500),
    reg_id character varying(255),
    "timestamp" timestamp(6) with time zone,
    CONSTRAINT chk_registration_events_action CHECK (((action)::text = ANY (ARRAY[('SUBMITTED'::character varying)::text, ('VERIFIED'::character varying)::text, ('REJECTED'::character varying)::text]))),
    CONSTRAINT chk_registration_events_actor_role CHECK (((actor_role)::text = ANY (ARRAY[('STUDENT'::character varying)::text, ('ADMIN'::character varying)::text, ('PRINCIPAL'::character varying)::text, ('HOD'::character varying)::text, ('DEPT_OFFICE'::character varying)::text, ('PROCTOR'::character varying)::text])))
);

--
-- Name: registration_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registration_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registration_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: registration_subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registration_subjects (
    reg_id character varying(255) NOT NULL,
    subject_id bigint NOT NULL
);

--
-- Name: registrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registrations (
    reg_id character varying(255) NOT NULL,
    registered_at timestamp(6) without time zone,
    status character varying(255),
    roll_no character varying(255),
    id bigint NOT NULL,
    verified_by character varying(255),
    snap_branch character varying(255) NOT NULL,
    snap_email character varying(255),
    snap_name character varying(255) NOT NULL,
    snap_phone character varying(255),
    snap_semester integer NOT NULL,
    snap_year_of_joining integer NOT NULL,
    version bigint,
    exam_cycle_id bigint NOT NULL,
    snap_academic_year integer,
    CONSTRAINT chk_registrations_status CHECK (((status)::text = ANY (ARRAY[('SUBMITTED'::character varying)::text, ('VERIFIED'::character varying)::text, ('REJECTED'::character varying)::text])))
);

--
-- Name: registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: student_semester_terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_semester_terms (
    id bigint NOT NULL,
    academic_year integer NOT NULL,
    roll_no character varying(255) NOT NULL,
    semester integer NOT NULL
);

--
-- Name: student_semester_terms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_semester_terms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_semester_terms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    roll_no character varying(255) NOT NULL,
    branch character varying(255),
    current_semester integer NOT NULL,
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    year_of_joining integer NOT NULL,
    date_of_birth date,
    entry_semester integer DEFAULT 1 NOT NULL,
    password_hash character varying(255)
);

--
-- Name: subject_eligible_departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subject_eligible_departments (
    subject_id bigint NOT NULL,
    dept_id bigint NOT NULL
);

--
-- Name: subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subjects (
    id bigint NOT NULL,
    semester integer NOT NULL,
    subject_name character varying(255),
    dept_id bigint,
    course_code character varying(255),
    credits integer DEFAULT 0 NOT NULL,
    subject_type character varying(255),
    academic_year_offered integer DEFAULT 0 NOT NULL,
    year_of_joining integer,
    CONSTRAINT chk_subjects_subject_type CHECK (((subject_type)::text = ANY (ARRAY[('REGULAR'::character varying)::text, ('ELECTIVE'::character varying)::text])))
);

--
-- Name: subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    username character varying(255) NOT NULL,
    password character varying(255),
    role character varying(255),
    dept_id bigint,
    CONSTRAINT chk_users_role CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('PRINCIPAL'::character varying)::text, ('HOD'::character varying)::text, ('DEPT_OFFICE'::character varying)::text, ('PROCTOR'::character varying)::text])))
);

--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);

--
-- Name: exam_cycles exam_cycles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_cycles
    ADD CONSTRAINT exam_cycles_pkey PRIMARY KEY (id);

--
-- Name: progression_batch_students pk_progression_batch_students; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progression_batch_students
    ADD CONSTRAINT pk_progression_batch_students PRIMARY KEY (id);

--
-- Name: progression_batches pk_progression_batches; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progression_batches
    ADD CONSTRAINT pk_progression_batches PRIMARY KEY (id);

--
-- Name: proctor_students proctor_students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctor_students
    ADD CONSTRAINT proctor_students_pkey PRIMARY KEY (roll_no);

--
-- Name: registration_events registration_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_events
    ADD CONSTRAINT registration_events_pkey PRIMARY KEY (id);

--
-- Name: registration_subjects registration_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_subjects
    ADD CONSTRAINT registration_subjects_pkey PRIMARY KEY (reg_id, subject_id);

--
-- Name: registrations registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT registrations_pkey PRIMARY KEY (reg_id);

--
-- Name: student_semester_terms student_semester_terms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_semester_terms
    ADD CONSTRAINT student_semester_terms_pkey PRIMARY KEY (id);

--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (roll_no);

--
-- Name: subject_eligible_departments subject_eligible_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_eligible_departments
    ADD CONSTRAINT subject_eligible_departments_pkey PRIMARY KEY (subject_id, dept_id);

--
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);

--
-- Name: student_semester_terms uk_student_semester; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_semester_terms
    ADD CONSTRAINT uk_student_semester UNIQUE (roll_no, semester);

--
-- Name: departments uka98yj7l53srcy6e08grm1tw90; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT uka98yj7l53srcy6e08grm1tw90 UNIQUE (dept_code);

--
-- Name: registrations uq_registrations_reg_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT uq_registrations_reg_id UNIQUE (reg_id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);

--
-- Name: idx_progression_batch_students_batch_notpromoted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_progression_batch_students_batch_notpromoted ON public.progression_batch_students USING btree (batch_id, outcome, roll_no) WHERE ((outcome)::text <> 'PROMOTED'::text);

--
-- Name: idx_progression_batches_run_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_progression_batches_run_at ON public.progression_batches USING btree (run_at DESC);

--
-- Name: ix_proctor_students_proctor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_proctor_students_proctor ON public.proctor_students USING btree (proctor_username);

--
-- Name: ix_registration_events_reg_id_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_registration_events_reg_id_time ON public.registration_events USING btree (reg_id, "timestamp");

--
-- Name: ix_registration_subjects_subject_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_registration_subjects_subject_id ON public.registration_subjects USING btree (subject_id);

--
-- Name: ix_registrations_cycle_status_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_registrations_cycle_status_time ON public.registrations USING btree (exam_cycle_id, status, registered_at);

--
-- Name: ix_registrations_roll_no_registered_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_registrations_roll_no_registered_at ON public.registrations USING btree (roll_no, registered_at);

--
-- Name: ix_students_branch_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_students_branch_lower ON public.students USING btree (lower((branch)::text));

--
-- Name: ix_students_name_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_students_name_trgm ON public.students USING gin (lower((name)::text) public.gin_trgm_ops);

--
-- Name: ix_students_roll_no_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_students_roll_no_trgm ON public.students USING gin (lower((roll_no)::text) public.gin_trgm_ops);

--
-- Name: ix_subject_eligible_departments_dept_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_subject_eligible_departments_dept_id ON public.subject_eligible_departments USING btree (dept_id);

--
-- Name: ix_subjects_year_semester; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_subjects_year_semester ON public.subjects USING btree (academic_year_offered, semester);

--
-- Name: uq_exam_cycles_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_exam_cycles_name ON public.exam_cycles USING btree (name);

--
-- Name: uq_exam_cycles_single_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_exam_cycles_single_active ON public.exam_cycles USING btree (active) WHERE (active = true);

--
-- Name: uq_pending_reg_per_cycle; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_pending_reg_per_cycle ON public.registrations USING btree (roll_no, exam_cycle_id) WHERE ((status)::text = 'SUBMITTED'::text);

--
-- Name: uq_registrations_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_registrations_id ON public.registrations USING btree (id);

--
-- Name: uq_subjects_code_year; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_subjects_code_year ON public.subjects USING btree (course_code, academic_year_offered);

--
-- Name: registrations fk69oiykyuu1vw227bguc1wdavr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT fk69oiykyuu1vw227bguc1wdavr FOREIGN KEY (exam_cycle_id) REFERENCES public.exam_cycles(id);

--
-- Name: proctor_students fk_proctor_students_proctor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctor_students
    ADD CONSTRAINT fk_proctor_students_proctor FOREIGN KEY (proctor_username) REFERENCES public.users(username) ON DELETE CASCADE;

--
-- Name: proctor_students fk_proctor_students_student; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctor_students
    ADD CONSTRAINT fk_proctor_students_student FOREIGN KEY (roll_no) REFERENCES public.students(roll_no) ON DELETE CASCADE;

--
-- Name: progression_batch_students fk_progression_batch_students_batch; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progression_batch_students
    ADD CONSTRAINT fk_progression_batch_students_batch FOREIGN KEY (batch_id) REFERENCES public.progression_batches(id) ON DELETE CASCADE;

--
-- Name: registration_events fk_registration_events_reg_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_events
    ADD CONSTRAINT fk_registration_events_reg_id FOREIGN KEY (reg_id) REFERENCES public.registrations(reg_id);

--
-- Name: subjects fkagcibl3s2punqkd7e3shuct9c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT fkagcibl3s2punqkd7e3shuct9c FOREIGN KEY (dept_id) REFERENCES public.departments(id);

--
-- Name: subject_eligible_departments fkbw6mvyjk0yc5lhow97de4qw0b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_eligible_departments
    ADD CONSTRAINT fkbw6mvyjk0yc5lhow97de4qw0b FOREIGN KEY (dept_id) REFERENCES public.departments(id);

--
-- Name: subject_eligible_departments fkelabgxscouqw0no41fmkfm4q1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_eligible_departments
    ADD CONSTRAINT fkelabgxscouqw0no41fmkfm4q1 FOREIGN KEY (subject_id) REFERENCES public.subjects(id);

--
-- Name: registration_subjects fkk6e8w8e2wdqm87eusb3kddca0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_subjects
    ADD CONSTRAINT fkk6e8w8e2wdqm87eusb3kddca0 FOREIGN KEY (reg_id) REFERENCES public.registrations(reg_id);

--
-- Name: users fkny8a9c8evadqjfx8jvetc73gs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkny8a9c8evadqjfx8jvetc73gs FOREIGN KEY (dept_id) REFERENCES public.departments(id);

--
-- Name: registration_subjects fkssr1w3t17rhy0c3q4epowu3rt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_subjects
    ADD CONSTRAINT fkssr1w3t17rhy0c3q4epowu3rt FOREIGN KEY (subject_id) REFERENCES public.subjects(id);

--
-- Name: registrations fktgn40ul7ir2551h1t090myxs7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT fktgn40ul7ir2551h1t090myxs7 FOREIGN KEY (roll_no) REFERENCES public.students(roll_no);

--
--

