-- P3-9: privilege changes left no trace anywhere — no audit row, no log line, and there is no
-- access log either. Coverage was INVERTED relative to impact: registration lifecycle and bulk
-- progression (things done TO a student) were fully audited, while what a privileged staff member
-- does — granting a role, opening registration college-wide, exporting everyone's data — left
-- nothing at all.
--
-- One generic table rather than one per resource: every row has the same shape (who, what, to
-- which thing, when), there is exactly one writer, and "what did this account do?" stays a single
-- query. Shaped after registration_events, which has worked well.
--
-- Append-only by convention, as registration_events is: rows are inserted, never updated or
-- deleted. Deliberately NO foreign keys — an audit row must outlive the thing it describes, and a
-- USER_DELETE row whose FK cascaded away would be worse than useless.
CREATE TABLE admin_audit_events (
    id bigint NOT NULL,
    action character varying(40) NOT NULL,
    actor character varying(255) NOT NULL,
    actor_role character varying(255),
    target_type character varying(30) NOT NULL,
    -- varchar, not bigint: targets are usernames, numeric ids and course codes alike.
    target_id character varying(255),
    detail character varying(500),
    "timestamp" timestamp(6) with time zone NOT NULL,
    CONSTRAINT chk_admin_audit_events_actor_role CHECK (((actor_role)::text = ANY (ARRAY[
        ('ADMIN'::character varying)::text,
        ('PRINCIPAL'::character varying)::text,
        ('HOD'::character varying)::text,
        ('DEPT_OFFICE'::character varying)::text,
        ('PROCTOR'::character varying)::text])))
);

-- No CHECK on `action`: unlike registration_events' three fixed states, this vocabulary grows every
-- time an audited operation is added, and a CHECK would force a migration for each one. The enum in
-- AdminAuditAction is the control; the column length is the only DB-level guard.

ALTER TABLE admin_audit_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin_audit_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY admin_audit_events
    ADD CONSTRAINT admin_audit_events_pkey PRIMARY KEY (id);

-- The two questions this table exists to answer: "what did this account do?" and "who touched this
-- thing?". Both are unindexed table scans otherwise.
CREATE INDEX idx_admin_audit_events_actor ON admin_audit_events (actor, "timestamp" DESC);
CREATE INDEX idx_admin_audit_events_target ON admin_audit_events (target_type, target_id);
