-- `username` was the PK of `users`, the target of proctor_students' FK, and the JWT subject, so it
-- could not be changed: JPA cannot update an @Id (setUsername + save INSERTS a second row), and the
-- FK carried ON DELETE CASCADE but no ON UPDATE CASCADE, so a raw UPDATE failed for any proctor
-- holding students. This makes identity a surrogate id and demotes username to a plain unique
-- attribute, which is what makes renaming possible at all.
--
-- The security principal deliberately stays the USERNAME (JwtService subject, auth.getName()).
-- Only the DATABASE key changes. Consequence, kept on purpose: a rename no longer resolves in
-- AccountExistenceFilter, which 401s and signs that account out — the "revoke, never silently swap"
-- rule from docs/adr/auth-scoping.md.
--
-- History columns holding usernames (registrations.verified_by, registration_events.actor,
-- admin_audit_events.actor/target_id, progression_batches.actor_username, proctor_students
-- .assigned_by) are deliberately NOT touched: they are snapshots of who someone WAS, and V3 states
-- an audit row must outlive the thing it describes. After a rename they show the old name.

-- Existing rows are back-filled by this single statement (identity fills on the table rewrite);
-- the sequence then resumes past them, so a later INSERT cannot collide.
ALTER TABLE users ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;

ALTER TABLE proctor_students ADD COLUMN proctor_user_id bigint;
UPDATE proctor_students ps SET proctor_user_id = u.id
    FROM users u WHERE u.username = ps.proctor_username;
ALTER TABLE proctor_students ALTER COLUMN proctor_user_id SET NOT NULL;

-- Order is load-bearing: the FK's index backs users_pkey, so dropping the PK first fails with
-- "cannot drop constraint users_pkey ... constraint fk_proctor_students_proctor depends on index".
ALTER TABLE proctor_students DROP CONSTRAINT fk_proctor_students_proctor;
ALTER TABLE users DROP CONSTRAINT users_pkey;
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Username stays globally unique — it is still the login credential and the JWT subject. Exact
-- match, as the PK was: 'Admin' and 'admin' remain distinct accounts, unchanged by this migration.
ALTER TABLE users ADD CONSTRAINT uq_users_username UNIQUE (username);

ALTER TABLE proctor_students ADD CONSTRAINT fk_proctor_students_proctor
    FOREIGN KEY (proctor_user_id) REFERENCES users(id) ON DELETE CASCADE;

-- Dropping the column takes ix_proctor_students_proctor with it; recreate it on the new column.
ALTER TABLE proctor_students DROP COLUMN proctor_username;
CREATE INDEX ix_proctor_students_proctor ON proctor_students USING btree (proctor_user_id);
