-- Scheduled reminder emails to students with VERIFIED registrations in an exam cycle.
--
-- A reminder stores the AUDIENCE RULE (cycle + optional department), never a recipient list: the
-- list is resolved when it sends, so registrations verified after scheduling are included and ones
-- rejected since are not. reminder_recipients is the send LOG — one row per student actually
-- attempted — and its unique key is what makes a re-run (cron retry, crash mid-send) skip anyone
-- already handled.
--
-- department_code is the branch code as TEXT, not a department FK: departments are deletable, and
-- ON DELETE SET NULL would silently widen a department reminder to the whole college.
CREATE TABLE reminders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_cycle_id bigint NOT NULL REFERENCES exam_cycles (id),
    department_code character varying(16),
    subject character varying(150) NOT NULL,
    message character varying(4000) NOT NULL,
    send_at timestamp(6) with time zone NOT NULL,
    status character varying(16) NOT NULL,
    created_by character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    started_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    cancelled_by character varying(255),
    cancelled_at timestamp(6) with time zone,
    last_error character varying(500),
    -- optimistic lock: a cancel racing the runner's SCHEDULED -> SENDING must lose, not overwrite
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT chk_reminders_status CHECK (status IN ('SCHEDULED', 'SENDING', 'SENT', 'CANCELLED'))
);

-- The runner's only question: "what is due?" — asked of unfinished reminders alone.
CREATE INDEX ix_reminders_due ON reminders (send_at) WHERE status IN ('SCHEDULED', 'SENDING');

-- No FK on roll_no: a history row, like registration_events.actor — it records who was emailed.
CREATE TABLE reminder_recipients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reminder_id bigint NOT NULL REFERENCES reminders (id),
    roll_no character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    outcome character varying(16) NOT NULL,
    error character varying(500),
    processed_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uq_reminder_recipients_reminder_roll UNIQUE (reminder_id, roll_no),
    CONSTRAINT chk_reminder_recipients_outcome CHECK (outcome IN ('SENT', 'FAILED'))
);

-- The daily-cap count: SENT rows in the last 24 hours.
CREATE INDEX ix_reminder_recipients_processed ON reminder_recipients (processed_at);
